import type { Metadata } from "next";
import localFont from "next/font/local";
import {Cairo} from 'next/font/google'
import "./globals.css";
import Header from "@/components/header/header";
import { Footer } from "@/components/Footer";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const cairo = Cairo({subsets:['arabic']})
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Cloud Hosting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen ${cairo.className} ${geistSans.variable} antialiased`}
      >
         <Header />
         <main>
        {children}

         </main>
        <ToastContainer 
        theme="colored" position="top-center"
        />
        <Footer />
      </body>
    </html>
  );
}
